Handle the case where diag_attributes_cmd_line_overrides is None
When there are no cmd line overrides, diag_attributes_cmd_line_overrides
is None and we hit following error when running the diag:

Command:
./jumpstart/scripts/build_diag.py  --diag_build ./build/  \
--diag_src ./diags/interrupts/s_int_file/  --keep_meson_builddir  \
--override_meson_options=spike_timeout=120 --override_meson_options=soc_rev=B0 \
--active_hart_mask_override "0b1111"  -v

Error:
File "/home/rkanwal/workspace/repos/rvsys/ctest/jumpstart/scripts/build_tools/diag.py", line 150, in __init__
    self.diag_attributes_cmd_line_overrides = [] if diag_attributes_cmd_line_overrides in None else diag_attributes_cmd_line_overrides
TypeError: argument of type 'NoneType' is not iterable

Signed-off-by: Rajnesh Kanwal <rkanwal@rivosinc.com>